version: '3'
services:
  mysql-standalone:
    image: 'mysql:8'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    ports:
      - "3307:3306"
  app:
    depends_on:
      - mysqldb
    build: 
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/demo?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root" 
      
     
    depends_on:
      - mysql-standalone
