name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.DO_KEY}} # Private or public key of the server
          username: ${{ secrets.DO_USERNAME }} # User of the server you want to ssh into
     
          script: |
            rm -rf test
            mkdir test 
            cd test 
            echo 'test folder 
            git clone https://github.com/swethamenonr/bookbackend.git
            echo 'Deployment successful to digital ocean'
