# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy on DO droplet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/ssh-action@v.0.1.3
    - name: Deploy to digital ocean via ssh action
      with:
        host: ${{secrets.DO
        password: ${{secrets_HOST}}
        username: ${{Secrets.DO_USERNAEM}}.DO_KEY}}
        script:
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)
          docker rmi $(docker images -q)
          cd spring-boot-backend-part
          git config --global credential.helper cache
          git pull

          docker-compose up --build
